export default () => ({
  nodeEnv: process.env.NODE_ENV ?? 'development',
  port: Number(process.env.PORT ?? 3001),
  databaseUrl: process.env.DATABASE_URL,
  jwtSecret: process.env.JWT_SECRET ?? 'change-me',
  jwtExpiresIn: process.env.JWT_EXPIRES_IN ?? '7d',
  frontendUrl: process.env.FRONTEND_URL ?? 'http://localhost:3000',
  adminUrl: process.env.ADMIN_URL ?? 'http://localhost:3002',
  appUrl: process.env.APP_URL ?? 'http://localhost:3001',
  publicSiteUrl: process.env.PUBLIC_SITE_URL ?? 'https://www.jssngyl.cn',
  baiduSite: process.env.BAIDU_SITE,
  baiduToken: process.env.BAIDU_TOKEN,
  allowedOrigins: process.env.ALLOWED_ORIGINS ?? '',
  uploadRoot: process.env.UPLOAD_ROOT ?? 'uploads',
  uploadMaxFileSizeMb: Number(process.env.UPLOAD_MAX_FILE_SIZE_MB ?? 10),
  adminLoginMaxAttempts: Number(process.env.ADMIN_LOGIN_MAX_ATTEMPTS ?? 5),
  adminLoginLockMinutes: Number(process.env.ADMIN_LOGIN_LOCK_MINUTES ?? 15),
});
