/** English reading copy; case membership and return paths remain in buyer-selection-guides.ts. */
export const buyerSelectionCopyEn: Record<string, {
  title: string; answer: string;
  options: { name: string; when: string; confirm: string }[];
  points: { title: string; text: string }[];
  next: string[]; limits: string;
}> = {
  'bearing-wire': {
    title: 'Which furnace should you choose for spheroidising bearing-steel wire?',
    answer: 'Compare bogie-hearth loading, a pit furnace with a retort, and a bell-furnace arrangement. First establish steel grade and prior condition, coil dimensions, net workpiece weight, surface and atmosphere requirements, then check handling, cooling and factory space. A bogie suits batch loading on a moving hearth; protective-atmosphere retorts require separate comparisons of sealing, lifting and batch scheduling. These records support configuration comparisons, not a universal furnace choice or process curve for a steel grade.',
    options: [
      { name: 'Bogie-hearth loading', when: 'Coils can stand securely on the hearth and the factory can accommodate bogie travel, rails and lifting.', confirm: 'Separate workpiece and tooling weights. Confirm support points, heat transfer from below, coil count and measuring positions. Review atmosphere provisions separately when surface condition matters.' },
      { name: 'Pit furnace with a retort', when: 'Coils fit the retort and flow-guiding arrangement, overhead lifting is available, and sealing, cooling water and gas utilities can be provided.', confirm: 'Distinguish the effective working zone from retort dimensions. Check upper and lower seals, water cooling, gas inlet/exhaust and hot handling separately.' },
      { name: 'Bell furnace with alternating use of bases', when: 'The load can stand on fixed bases and a crane can move the hoods, with heating and cooling occupancy included in planning.', confirm: 'Coordinate heating hoods, bases, retorts and cooling hoods against the whole batch cycle. Do not multiply output by the number of bases.' },
    ],
    points: [
      { title: 'Check how the complete coil load sits on the bogie', text: 'Record 068 describes coils approximately 1.3 m in diameter and 1.7 m high, with 30 t excluding tooling. This supports asking for coil geometry and tooling weight instead of only a “30-tonne furnace”. The source includes spheroidising parameters but also different wording for the application; its cover date 23 April 2017, document number date 21 April 2017 and closing date 26 August 2016 differ. Resolve the version and intended process before selection; temperature alone does not identify the process.' },
      { title: 'Compare atmosphere protection together with sealing and water cooling', text: 'Record 056 explicitly discusses wire spheroidising and a bottomless retort, separating the water-cooled lower oil seal from the upper seal. Eight coils at 2.1 t are about 16.8 t; a 16–20 t range does not establish a 20 t net load. The arrangement shows why loading, seals, water and gas must be checked together. The closing date 15 May 2020 differs from the cover date 18 May 2026. These structures are not standard on every pit furnace.' },
      { title: 'Verify the complete batch schedule before assigning output', text: 'Record 054 lists one heating hood, two bases with retorts and one cooling hood. It discusses ten 2 t coils and 24 hours per batch, without agreeing which stages that period includes. This does not establish 40 t per day. It supports scheduling loading, hood placement, heating, cooling, hood moves and crane waits individually; it does not prove higher output than pit or bogie-hearth alternatives. The closing date 27 April 2020 and cover date 18 May 2026 require version confirmation.' },
    ],
    next: ['Provide the grade, previous processing, required spheroidised structure or hardness, surface requirements and any confirmed process curve. List unresolved items for verification.', 'Provide coil inner/outer diameters, height, weight, loading and tooling drawings, and the available crane, rails, gas and cooling water.', 'Compare complete cycles, supply boundaries and workpiece inspection under the same representative load before fixing configuration and quotation.'],
    limits: 'These historical proposals have date or version differences and provide no comparable measured throughput, energy use, spheroidised structure or acceptance reports. They do not establish a universal temperature curve, guaranteed full-load output or the best furnace type. The applicable technical version and final design remain subject to confirmation.',
  },
  'trolley-renovation': {
    title: 'What should you confirm before renovating an existing bogie-hearth furnace?',
    answer: 'Confirm the problem to solve, the actual condition of the existing furnace, the parts to retain and every old-to-new interface before setting the shutdown window and acceptance method. Lengthening, fuel conversion, relining and control upgrades affect different systems. If drawings disagree with the site or loading and utilities are unclear, measure and inspect first; then compare local repair, system renovation and replacement.',
    options: [
      { name: 'Local repair', when: 'The defect is identified, retained structures and systems remain suitable after inspection, and the process and loading requirements have not materially changed.', confirm: 'Define the damage, unknown items requiring dismantling, repair boundaries and retesting. Existing records cannot guarantee that a local repair is sufficient.' },
      { name: 'System renovation', when: 'Length, fuel, zoning or controls will change and old equipment must work with new parts.', confirm: 'Freeze retained, replaced, added and buyer-supplied items individually. Check rails, foundations, air/flue paths, power, signals and whole-furnace testing.' },
      { name: 'Compare complete replacement', when: 'Inspection finds structures, interfaces or process suitability difficult to retain, or renovation risks and shutdown arrangements are unacceptable.', confirm: 'Compare new equipment under the same workpiece, objectives and supply scope. Without a site diagnosis, neither lower cost nor shorter downtime can be promised.' },
    ],
    points: [
      { title: 'Lengthening also changes heat load, zones and running gear', text: 'Record 067, dated 23 June 2019, extends the effective length from 7 m to 10 m, adds 300 kW to 750 kW and two zones to six, adds wheels and rails, and requires whole-furnace retesting. These connected changes support checking power, structural load, travel and the combined zones before defining the work. A record from the original six zones cannot replace acceptance testing of the modified eight-zone furnace.' },
      { title: 'Retained fans and flues still need their operating conditions checked', text: 'Record 013, dated 13 November 2018, retains the oil system and adds 16 natural-gas burners. Both modes share existing combustion-air and exhaust systems, with new air branches and changeover equipment. Reuse therefore still requires flow, pressure, isolation, mode switching and fault-protection checks. The source does not confirm simultaneous co-firing, and 16 furnace-temperature zones are not the separately optional 24 workpiece recording points.' },
      { title: 'Separate detection, options and buyer-supplied items before converting fuel', text: 'Record 069, dated 26 February 2018, discusses conversion from cold coal gas to natural gas while retaining the counts of eight burners and four zones. Fuel pipes would be renewed and some air/flue equipment retained. Two oxygen analysers are optional and two carbon-monoxide alarms are buyer-supplied; they serve different functions. This supports an itemised gas, piping, valve, detection and protection checklist. It does not establish automatic oxygen feedback, savings or improved surface quality.' },
    ],
    next: ['Provide furnace and rail photos, original drawings, earlier modifications, fault descriptions and current loading/temperature records, identifying uninspected areas.', 'State the new workpiece and process objectives, power or gas conditions and allowable shutdown window. List retained, replaced, added and site-supplied items.', 'Have equipment and site personnel confirm interfaces, construction stages, contingency arrangements and the modified whole-furnace test outline before agreeing schedule and price.'],
    limits: 'All three records are proposals, without proof of execution or acceptance. Current equipment condition and site utilities have not been verified. They support no fixed downtime, standard price, energy-saving percentage or remaining service life. Final combustion protection and structural design require technical confirmation.',
  },
  'box-transfer': {
    title: 'How should you choose a box-furnace unloading and water-quench transfer arrangement?',
    answer: 'Specify the required cooling medium and the permitted time for the workpiece to reach it, then compare the entire handling path. Tray push/pull transfer can deliver to an external receiving position; charging forks can pick up the workpiece with tooling, travel and lower it into water. A bogie exiting the furnace still needs a defined onward cooling transfer. Door-opening time and tray-delivery time are not automatically full-immersion time.',
    options: [
      { name: 'Push/pull the tray outside the furnace', when: 'The batch and tray suit roller support and an operator or mechanism is defined at the receiving point.', confirm: 'Confirm discharge height, distance, basket dimensions and receiving actions. If immersion is needed, add the subsequent pickup, travel and lowering times.' },
      { name: 'Fork pickup and transfer into water', when: 'The workpiece or basket has a stable fork-bearing surface, centre of gravity and hot load can be checked, and the tank and travel path can be coordinated.', confirm: 'Use one loading drawing for supports, forks, basket, furnace opening, water level and lowering stroke. Agree the event that marks complete immersion.' },
      { name: 'Bogie exit followed by onward transfer', when: 'Bogie-supported loading is needed and a separate cooling path can meet the process requirements.', confirm: 'Define who picks up the load, where it goes and any waits after furnace exit. Bogie capacity alone does not establish rapid immersion capability.' },
    ],
    points: [
      { title: 'Compare the same end event before comparing seconds', text: 'Record 038, dated 24 July 2023, limits “not more than 5–7 seconds” to door opening through tray delivery to position; the final threshold still needs agreement and onward immersion is undefined. Record 006, dated 12 February 2023, gives workpiece exit to immersion within 30 seconds without detailing the events; its accompanying bogie proposal has no equivalent metric. Together they support drawing the full sequence first. They do not prove that the 5–7-second arrangement immerses faster or that the two furnaces are interchangeable.' },
      { title: 'A load fitting inside the furnace may still exceed the transfer allowance', text: 'Record 077, dated 17 December 2016, gives furnace loading of 5–8 t per batch excluding tooling/support blocks. The handling machine is specified at not less than 8 t under uniformly distributed loading, including tooling. This supports separate workpiece, basket and travelling-tooling weights, followed by hot support, centre-of-gravity and travel checks. “Not less than 8 t” neither fixes maximum capacity at 8 t nor proves the ability to transfer 8 t of net workpieces.' },
      { title: 'Buyer-supplied baskets and tanks must join the same interface review', text: 'Record 032 has a closing date of 20 March 2024 and a cover date of 19 March. The basket and water tank are buyer-supplied, with about 45 seconds from furnace exit to immersion. Effective dimensions are recorded as 1.2 × 6 × 0.6 m in the original directions; length and width must not be silently exchanged. Basket weight, support positions, fork clearance, tank position and water level affect the complete arrangement. Automatic water makeup does not prove water-temperature control or cooling capacity, and about 45 seconds is not a guaranteed door-opening-to-full-immersion time.' },
    ],
    next: ['Provide material, workpiece and loading drawings, net and tooling weights, target process, and the start/end events for the permitted transfer time.', 'Mark the door, receiving point, tracks/travel area, tank, water level and existing equipment on the factory layout. Confirm design, supply and installation responsibilities.', 'Check door positions, fork pickup, travel, immersion and receiving the next batch under a representative load, then verify cooling conditions and workpiece results separately.'],
    limits: 'These records provide no measured complete-immersion tests or workpiece acceptance results. Equipment temperature alone, such as 1200°C, cannot identify the process. Single-stage times cannot rank overall performance, and one project’s tank, forks or loading arrangement is not a standard configuration for every box furnace.',
  },
};
